#!/usr/bin/env python3
import os

CFG = "/boot/grub/grub.cfg"

# Read the generated grub config
with open(CFG, 'r') as f:
    text = f.read()

# INJECT CLASSES so the Matrix theme can find your images!
text = text.replace("submenu 'Advanced options for ", "submenu --class adv_arch 'Advanced options for ")
text = text.replace("menuentry 'UEFI Firmware Settings'", "menuentry --class uefi 'UEFI Firmware Settings'")

# Locate the Windows block generated by os-prober
os_prober_start = text.find("### BEGIN /etc/grub.d/30_os-prober ###")
os_prober_end = text.find("### END /etc/grub.d/30_os-prober ###")

if os_prober_start != -1 and os_prober_end != -1:
    os_prober_end += len("### END /etc/grub.d/30_os-prober ###")
    os_prober_block = text[os_prober_start:os_prober_end]
    
    # Remove the Windows block from the bottom
    text = text[:os_prober_start] + text[os_prober_end:]
    
    # Locate the start of the Advanced Options submenu (now with the injected class)
    submenu_start = text.find("submenu --class adv_arch 'Advanced options for ")
    
    if submenu_start != -1:
        # Insert the Windows block right between Arch Linux and Advanced Options
        text = text[:submenu_start] + os_prober_block + "\n" + text[submenu_start:]
        
        # Save the reordered config
        with open(CFG, 'w') as f:
            f.write(text)
        print("=> GRUB menu successfully reordered and classes injected: 1. Arch 2. Windows 3. Advanced 4. UEFI")
    else:
        # Save config anyway to keep the class injections
        with open(CFG, 'w') as f:
            f.write(text)
        print("=> Could not find Advanced Options submenu, skipping reorder. Classes were still injected.")
else:
    # Save config anyway to keep the class injections
    with open(CFG, 'w') as f:
        f.write(text)
    print("=> Could not find Windows os-prober block, skipping reorder. Classes were still injected.")
