#!/usr/bin/env python3
import os
import re

CFG = "/boot/grub/grub.cfg"

# Read the generated grub config
with open(CFG, 'r') as f:
    text = f.read()

# INJECT CLASSES so the Matrix theme can find your images!
# GRUB syntax requires options (--class) to come AFTER the title string.
if "--class adv_arch" not in text:
    text = re.sub(r"(submenu\s+['\"].*?Advanced options for[^'\"]+['\"])", r"\1 --class adv_arch", text)
if "--class uefi" not in text:
    text = re.sub(r"(menuentry\s+['\"]UEFI Firmware Settings['\"])", r"\1 --class uefi", text)

# Locate the Windows block generated by os-prober
os_prober_start = text.find("### BEGIN /etc/grub.d/30_os-prober ###")
os_prober_end = text.find("### END /etc/grub.d/30_os-prober ###")

if os_prober_start != -1 and os_prober_end != -1:
    os_prober_end += len("### END /etc/grub.d/30_os-prober ###")
    os_prober_block = text[os_prober_start:os_prober_end]
    
    # Remove the Windows block from the bottom
    text_without_windows = text[:os_prober_start] + text[os_prober_end:]
    
    # Locate the start of the Advanced Options submenu in the text without Windows
    submenu_match = re.search(r"submenu\s+['\"].*?Advanced options for", text_without_windows)
    
    if submenu_match:
        submenu_start = submenu_match.start()
        # Insert the Windows block right between Arch Linux and Advanced Options
        text = text_without_windows[:submenu_start] + os_prober_block + "\n" + text_without_windows[submenu_start:]
        print("=> GRUB menu successfully reordered and classes injected: 1. Arch 2. Windows 3. Advanced 4. UEFI")
    else:
        # If no submenu exists, just keep text as is (with Windows at the bottom)
        print("=> Could not find Advanced Options submenu, skipping reorder. Classes were still injected.")
else:
    print("=> Could not find Windows os-prober block, skipping reorder. Classes were still injected.")

# Save config
with open(CFG, 'w') as f:
    f.write(text)
